blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('create_post/', views.create_post, name='create_post'),
    path('<int:id>/<slug:slug>/', views.post, name='post'),
]

post/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    pub_date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    image = models.ImageField(upload_to='post/', blank=True)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
            return self.title

    def get_absolute_url(self):
            return reverse('post:post', args=[self.id, self.slug])

post/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'image')

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostCreateForm
from uuslug import slugify


def blog(request):
    last_post = Post.objects.first()
    posts = Post.objects.exclude(id=last_post.id)
    return render(request, 'blog.html', {'posts': posts,
                                         'last_post': last_post})

def post(request, id, slug):
    post = Post.objects.get(id=id, slug=slug)
    return render(request, 'post.html', {'post': post})

def create_post(request):
    if request.method == 'POST':
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            new = form.save(commit=False)
            new.slug = slugify(form.cleaned_data['title'])
            new.save()
            return redirect('post:blog')
    else:
        form = PostCreateForm
    return render(request, 'create_post.html', {'form': form})
    

post/templates/blog.html
{% extends "main.html" %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block content %} 

<div class="blog">
    <div class="blog_new">
        <span class="blog_new_new">NEW</span>

        <p class="blog_new_title">{{ last_post.title }}</p>
        <p class="blog_new_body">{{ last_post.body }}</p>
        <a href="{{ last_post.get_absolute_url }}"><button class="blog_new_btn">Читать</button></a>
    </div>
    <div class="blog_img"> 
        {% if last_post.image %}
        {% if last_post.id == 11 %}
        <img src="https://sun9-45.userapi.com/h_RMqtUw6lnPuOTkXu02ZE4MOiQnhiB0O3vKDw/Zktw7_EvQfY.jpg">
        {% else %}
        <img src="{{ last_post.image.url }}">
        {% endif %}
        {% endif %}
    </div>
</div>
<div class="blog_posts">
    <span class="blog_posts_another">Другие статьи</span>
    <div class="blog_posts_grid">
        {% for post in posts %}
        <div class="blog_posts_grid_post">
            <span class="blog_posts_grid_post_date">{{ post.pub_date|date:"d E Y H:i" }}</span>
            <div class="blog_posts_grid_post_img">
                {% if post.image %}
                {% if post.id == 10 %}
                <img src="https://sun9-37.userapi.com/rtParv9gSdxD159PPI6pcIBoAbT7xTwmKWOFNg/w8J4tAVlSvk.jpg">
                {% else %}
                <img src="{{ post.image.url }}">
                {% endif %}
                {% endif %}
            </div>
            <a class="blog_posts_grid_post_title" href="{{ post.get_absolute_url }}"><p>{{ post.title }}</p></a>
        </div> 
        {% endfor %} 
    </div>
</div>

{% endblock %}

post/templates/create_post.html
{% extends "main.html" %}
{% load static %}
{% block title %}New post{% endblock %}
{% block content %} 
<div class="add">
    <span class="add_post">Добавить статью</span>
    <form class="form_add" action="." method="post" enctype="multipart/form-data">
        <div>
            <label hidden for="id_title">Title:</label>
            <input type="text" name="title" maxlength="250" required="" id="id_title" placeholder="Введите название статьи">
            <input class="form_add_input_submit" type="submit" value="Опубликовать"> 
        </div>
        <div class="down">
            <label hidden for="id_body">Body:</label>
            <textarea name="body" cols="40" rows="10" required="" id="id_body"></textarea>
            <div class="form_add_image">
                <span class="form_add_image_sub">Загрузить изображение</span>
                <div id="prev" hidden>
                    <svg id="close" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="12" cy="12" r="12" fill="#E5E5E5"/>
                        <line x1="16.9498" y1="7.05025" x2="7.05029" y2="16.9497" stroke="white" stroke-width="2"/>
                        <line x1="16.9496" y1="16.9497" x2="7.05014" y2="7.05023" stroke="white" stroke-width="2"/>
                    </svg>   
                </div>
                <div id="preview">
                    <label class="form_add_image_btn" for="id_image"><span>Файл</span></label>
                    <input type="file" name="image" accept="image/*" id="id_image"> 
                </div>
            </div>
        </div>
        {% csrf_token %}
    </form>
</div>

<script>
    function showFile(e) {
    var f = e.target.files[0];
    var fr = new FileReader();
    fr.onload = (function(theFile) {
        return function(e) {
          var div = document.createElement('div');
          div.innerHTML = "<img src='" + e.target.result + "' />";
          div.setAttribute("id", "image");
          document.getElementById('prev').insertBefore(div, null);
          document.getElementById('prev').hidden=false;
          document.getElementById('preview').hidden=true;
        };
      })(f);
 
      fr.readAsDataURL(f);
    }

    document.getElementById('id_image').addEventListener('change', showFile, false);

    document.getElementById('close').onclick = function(){
        document.getElementById('image').innerHTML = "";
        document.getElementById('prev').hidden=true;
        document.getElementById('preview').hidden=false;
    }

</script>
{% endblock %}

post/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Blog{% endblock %}</title>
    <link href="{% static "css/main.css" %}" rel="stylesheet">
</head>
<body>
<header>
    <div class="header_menu">
        <div class="header_logo">
        </div>
        <div class="header_blog">
            <a href="{% url "post:blog" %}">Блог</a>
        </div>
    </div>
    <a href="{% url "post:create_post" %}"><button class="header_add_post_btn"><span>+ Добавить статью</span></button></a>
</header>
    {% block content %} 
    {% endblock %}
</body>
</html>

post/templates/post.html
{% extends "main.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %} 
<div class="post">
    <div class="post_">
        <p class="post_title">{{ post.title }}</p>
        {% if post.image %}
        <div class="post_img">
            <img src="{{ post.image.url }}">
        </div>
        {% endif %}
        <p class="post_body">{{ post.body }}</p>
    </div>
</div>

{% endblock %}